/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.democrapp.view;

/**
 *
 * @author DIEGO
 */
public class EdicionDeDatos extends javax.swing.JPanel {

    /**
     * Creates new form EdicionDeDatos
     */
    public EdicionDeDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEdicionDeDatos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();
        lblIconEdit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAtras = new javax.swing.JButton();
        lblNombrePartido = new javax.swing.JLabel();
        txtNombrePartido = new javax.swing.JTextField();
        lblSigla = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        lblNombreLider = new javax.swing.JLabel();
        txtNombreLider = new javax.swing.JTextField();
        lblIdeologia = new javax.swing.JLabel();
        txtIdeologia = new javax.swing.JTextField();
        lblAfiliados = new javax.swing.JLabel();
        txtAfiliados = new javax.swing.JTextField();
        lblDepartamento = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(57, 72, 98));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 450));
        setMinimumSize(new java.awt.Dimension(700, 450));

        jPanelEdicionDeDatos.setBackground(new java.awt.Color(81, 198, 186));
        jPanelEdicionDeDatos.setMaximumSize(new java.awt.Dimension(350, 450));
        jPanelEdicionDeDatos.setMinimumSize(new java.awt.Dimension(350, 450));
        jPanelEdicionDeDatos.setPreferredSize(new java.awt.Dimension(350, 450));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Edicion de Datos");

        lblDescripcion1.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDescripcion1.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion1.setText("En esta seccion puedes actualizar toda la");

        lblDescripcion2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDescripcion2.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion2.setText("informacion de un partido politico.");

        lblIconEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconEdit.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 8));

        javax.swing.GroupLayout jPanelEdicionDeDatosLayout = new javax.swing.GroupLayout(jPanelEdicionDeDatos);
        jPanelEdicionDeDatos.setLayout(jPanelEdicionDeDatosLayout);
        jPanelEdicionDeDatosLayout.setHorizontalGroup(
            jPanelEdicionDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdicionDeDatosLayout.createSequentialGroup()
                .addGroup(jPanelEdicionDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEdicionDeDatosLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblTitulo))
                    .addGroup(jPanelEdicionDeDatosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelEdicionDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion2)
                            .addComponent(lblDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEdicionDeDatosLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEdicionDeDatosLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblIconEdit)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelEdicionDeDatosLayout.setVerticalGroup(
            jPanelEdicionDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdicionDeDatosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitulo)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion2)
                .addGap(60, 60, 60)
                .addComponent(lblIconEdit)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        btnAtras.setBackground(new java.awt.Color(81, 198, 186));
        btnAtras.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("<");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lblNombrePartido.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombrePartido.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePartido.setText("Nombre del partido politico");

        txtNombrePartido.setBackground(new java.awt.Color(57, 72, 98));
        txtNombrePartido.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtNombrePartido.setForeground(new java.awt.Color(255, 255, 255));
        txtNombrePartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePartidoActionPerformed(evt);
            }
        });

        lblSigla.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSigla.setForeground(new java.awt.Color(255, 255, 255));
        lblSigla.setText("Sigla");

        txtSigla.setBackground(new java.awt.Color(57, 72, 98));
        txtSigla.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtSigla.setForeground(new java.awt.Color(255, 255, 255));

        lblNombreLider.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombreLider.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreLider.setText("Nombre del lider");

        txtNombreLider.setBackground(new java.awt.Color(57, 72, 98));
        txtNombreLider.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtNombreLider.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreLider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreLiderActionPerformed(evt);
            }
        });

        lblIdeologia.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblIdeologia.setForeground(new java.awt.Color(255, 255, 255));
        lblIdeologia.setText("Ideologia");

        txtIdeologia.setBackground(new java.awt.Color(57, 72, 98));
        txtIdeologia.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtIdeologia.setForeground(new java.awt.Color(255, 255, 255));
        txtIdeologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdeologiaActionPerformed(evt);
            }
        });

        lblAfiliados.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblAfiliados.setForeground(new java.awt.Color(255, 255, 255));
        lblAfiliados.setText("Numero de afiliados");

        txtAfiliados.setBackground(new java.awt.Color(57, 72, 98));
        txtAfiliados.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtAfiliados.setForeground(new java.awt.Color(255, 255, 255));
        txtAfiliados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAfiliadosActionPerformed(evt);
            }
        });

        lblDepartamento.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartamento.setText("Departamento");

        txtDepartamento.setBackground(new java.awt.Color(57, 72, 98));
        txtDepartamento.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        txtDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartamentoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(81, 198, 186));
        btnGuardar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicionDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAtras)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombrePartido)
                                .addComponent(txtSigla)
                                .addComponent(txtNombreLider)
                                .addComponent(lblIdeologia, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdeologia)
                                .addComponent(lblAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAfiliados)
                                .addComponent(lblDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDepartamento)
                                .addComponent(lblNombrePartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSigla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombreLider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicionDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombrePartido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombrePartido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblSigla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblNombreLider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreLider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdeologia)
                .addGap(12, 12, 12)
                .addComponent(txtIdeologia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblAfiliados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtNombrePartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePartidoActionPerformed

    private void txtNombreLiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreLiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreLiderActionPerformed

    private void txtIdeologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdeologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdeologiaActionPerformed

    private void txtAfiliadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAfiliadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAfiliadosActionPerformed

    private void txtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanelEdicionDeDatos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAfiliados;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblIconEdit;
    private javax.swing.JLabel lblIdeologia;
    private javax.swing.JLabel lblNombreLider;
    private javax.swing.JLabel lblNombrePartido;
    private javax.swing.JLabel lblSigla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAfiliados;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtIdeologia;
    private javax.swing.JTextField txtNombreLider;
    private javax.swing.JTextField txtNombrePartido;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
