/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.democrapp.view;

/**
 *
 * @author DIEGO
 */
public class RegistroEdicionPartidos extends javax.swing.JFrame {

    /**
     * Creates new form RegistroDePartidos
     */
    public RegistroEdicionPartidos() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistroDeDatos = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelIzquierdo = new javax.swing.JPanel();
        panelRegistroVista = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();
        lblIconRegistro = new javax.swing.JLabel();
        panelDerecho = new javax.swing.JPanel();
        panelRegistro = new javax.swing.JPanel();
        btnAtrasRegistro = new javax.swing.JButton();
        lblIdentificador = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        lblDepartamento = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        lblNombrePartido = new javax.swing.JLabel();
        txtNombrePartido = new javax.swing.JTextField();
        lblSigla = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        lblIdeologia = new javax.swing.JLabel();
        txtIdeologia = new javax.swing.JTextField();
        lblNumAfiliados = new javax.swing.JLabel();
        txtNumAfiliados = new javax.swing.JTextField();
        lblFechaFundacion = new javax.swing.JLabel();
        txtFechaFundacion = new javax.swing.JTextField();
        btnGuardarRegistro = new javax.swing.JButton();
        lblNombreLider = new javax.swing.JLabel();
        txtNombreLider = new javax.swing.JTextField();
        panelPrincipal = new javax.swing.JPanel();
        btnRegistroDeDatos = new javax.swing.JButton();
        btnEdicionDeDatos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pilar1 = new javax.swing.JPanel();
        pilar2 = new javax.swing.JPanel();
        panelEdicionDeDatos = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        panelIzquierdoE = new javax.swing.JPanel();
        panelEdicionVista = new javax.swing.JPanel();
        lblTituloEdicion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTextoEdicion = new javax.swing.JLabel();
        lblTextoEdicion2 = new javax.swing.JLabel();
        panelTextoEdicion3 = new javax.swing.JLabel();
        panelDerechoE = new javax.swing.JPanel();
        panelEdicion = new javax.swing.JPanel();
        btnAtrasEdit = new javax.swing.JButton();
        lblNombrePartidoEdit = new javax.swing.JLabel();
        txtNombrePartidoEdit = new javax.swing.JTextField();
        lblSiglaEdit = new javax.swing.JLabel();
        txtSiglaEdit = new javax.swing.JTextField();
        lblNombreLiderEdit = new javax.swing.JLabel();
        txtNombreLiderEdit = new javax.swing.JTextField();
        lblIdeologiaEdit = new javax.swing.JLabel();
        txtIdeologiaEdit = new javax.swing.JTextField();
        lblNumeroAfiliadosEdit = new javax.swing.JLabel();
        txtNumeroAfiliadosEdit = new javax.swing.JTextField();
        lblDepartamentoEdit = new javax.swing.JLabel();
        txtDepartamentoEdit = new javax.swing.JTextField();
        btnGuardarEdit = new javax.swing.JButton();
        panelTablaEdicion = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        panelIzquierdoT = new javax.swing.JPanel();
        panelTablaVista = new javax.swing.JPanel();
        lblTituloTabla = new javax.swing.JLabel();
        lblTextoT1 = new javax.swing.JLabel();
        lblTextoT2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblIconTabla = new javax.swing.JLabel();
        panelDerechoT = new javax.swing.JPanel();
        panelTabla = new javax.swing.JPanel();
        btnAtrasTabla = new javax.swing.JButton();
        btnValidarTabla = new javax.swing.JButton();
        scrollTabla = new javax.swing.JScrollPane();
        tablaIdentificador = new javax.swing.JTable();
        lblIdentificadorTabla = new javax.swing.JLabel();
        txtIdentificadorTabla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));

        panelRegistroDeDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRegistroDeDatos.setMaximumSize(new java.awt.Dimension(700, 450));
        panelRegistroDeDatos.setMinimumSize(new java.awt.Dimension(700, 450));

        jSplitPane1.setDividerSize(0);

        panelIzquierdo.setBackground(new java.awt.Color(81, 198, 186));
        panelIzquierdo.setMaximumSize(new java.awt.Dimension(350, 450));
        panelIzquierdo.setMinimumSize(new java.awt.Dimension(350, 450));
        panelIzquierdo.setPreferredSize(new java.awt.Dimension(350, 450));
        panelIzquierdo.setLayout(new java.awt.CardLayout());

        panelRegistroVista.setBackground(new java.awt.Color(81, 198, 186));
        panelRegistroVista.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistroVista.setMaximumSize(new java.awt.Dimension(350, 450));
        panelRegistroVista.setMinimumSize(new java.awt.Dimension(350, 450));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro de Datos");

        lblTexto1.setBackground(new java.awt.Color(81, 198, 186));
        lblTexto1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto1.setText("Completa los datos necesarios para ");

        lblTexto2.setBackground(new java.awt.Color(81, 198, 186));
        lblTexto2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTexto2.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto2.setText("incluir tu partido. Por favor, asegurate");

        lblTexto3.setBackground(new java.awt.Color(81, 198, 186));
        lblTexto3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTexto3.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto3.setText("de que la informacion sea correcta.");

        lblIconRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconRegistro.png"))); // NOI18N
        lblIconRegistro.setToolTipText("");

        javax.swing.GroupLayout panelRegistroVistaLayout = new javax.swing.GroupLayout(panelRegistroVista);
        panelRegistroVista.setLayout(panelRegistroVistaLayout);
        panelRegistroVistaLayout.setHorizontalGroup(
            panelRegistroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroVistaLayout.createSequentialGroup()
                .addGroup(panelRegistroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroVistaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroVistaLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroVistaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelRegistroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTexto2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(lblTexto1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(lblTexto3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroVistaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIconRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        panelRegistroVistaLayout.setVerticalGroup(
            panelRegistroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroVistaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTexto3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblIconRegistro)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelIzquierdo.add(panelRegistroVista, "card2");

        jSplitPane1.setLeftComponent(panelIzquierdo);

        panelDerecho.setBackground(new java.awt.Color(57, 72, 98));
        panelDerecho.setMaximumSize(new java.awt.Dimension(350, 450));
        panelDerecho.setMinimumSize(new java.awt.Dimension(350, 450));
        panelDerecho.setPreferredSize(new java.awt.Dimension(350, 450));
        panelDerecho.setLayout(new java.awt.CardLayout());

        panelRegistro.setBackground(new java.awt.Color(57, 72, 98));
        panelRegistro.setMaximumSize(new java.awt.Dimension(350, 450));
        panelRegistro.setMinimumSize(new java.awt.Dimension(350, 450));
        panelRegistro.setPreferredSize(new java.awt.Dimension(350, 450));

        btnAtrasRegistro.setBackground(new java.awt.Color(81, 198, 186));
        btnAtrasRegistro.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAtrasRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasRegistro.setText("<");
        btnAtrasRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasRegistroActionPerformed(evt);
            }
        });

        lblIdentificador.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblIdentificador.setForeground(new java.awt.Color(255, 255, 255));
        lblIdentificador.setText("Identificador");

        txtIdentificador.setBackground(new java.awt.Color(57, 72, 98));
        txtIdentificador.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtIdentificador.setForeground(new java.awt.Color(255, 255, 255));

        lblDepartamento.setBackground(new java.awt.Color(57, 72, 98));
        lblDepartamento.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartamento.setText("ID de departamento");

        txtDepartamento.setBackground(new java.awt.Color(57, 72, 98));
        txtDepartamento.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtDepartamento.setForeground(new java.awt.Color(255, 255, 255));

        lblNombrePartido.setBackground(new java.awt.Color(57, 72, 98));
        lblNombrePartido.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombrePartido.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePartido.setText("Nombre del partido");

        txtNombrePartido.setBackground(new java.awt.Color(57, 72, 98));
        txtNombrePartido.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNombrePartido.setForeground(new java.awt.Color(255, 255, 255));
        txtNombrePartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePartidoActionPerformed(evt);
            }
        });

        lblSigla.setBackground(new java.awt.Color(57, 72, 98));
        lblSigla.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSigla.setForeground(new java.awt.Color(255, 255, 255));
        lblSigla.setText("Sigla");

        txtSigla.setBackground(new java.awt.Color(57, 72, 98));
        txtSigla.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSigla.setForeground(new java.awt.Color(255, 255, 255));

        lblIdeologia.setBackground(new java.awt.Color(57, 72, 98));
        lblIdeologia.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblIdeologia.setForeground(new java.awt.Color(255, 255, 255));
        lblIdeologia.setText("Ideologia");
        lblIdeologia.setToolTipText("");

        txtIdeologia.setBackground(new java.awt.Color(57, 72, 98));
        txtIdeologia.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtIdeologia.setForeground(new java.awt.Color(255, 255, 255));
        txtIdeologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdeologiaActionPerformed(evt);
            }
        });

        lblNumAfiliados.setBackground(new java.awt.Color(57, 72, 98));
        lblNumAfiliados.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNumAfiliados.setForeground(new java.awt.Color(255, 255, 255));
        lblNumAfiliados.setText("Numero de afiliados");

        txtNumAfiliados.setBackground(new java.awt.Color(57, 72, 98));
        txtNumAfiliados.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNumAfiliados.setForeground(new java.awt.Color(255, 255, 255));
        txtNumAfiliados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAfiliadosActionPerformed(evt);
            }
        });

        lblFechaFundacion.setBackground(new java.awt.Color(57, 72, 98));
        lblFechaFundacion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblFechaFundacion.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaFundacion.setText("Fecha de Fundacion YYYY-MM-DD");

        txtFechaFundacion.setBackground(new java.awt.Color(57, 72, 98));
        txtFechaFundacion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtFechaFundacion.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaFundacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFundacionActionPerformed(evt);
            }
        });

        btnGuardarRegistro.setBackground(new java.awt.Color(81, 198, 186));
        btnGuardarRegistro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGuardarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarRegistro.setText("Guardar");
        btnGuardarRegistro.setToolTipText("");

        lblNombreLider.setBackground(new java.awt.Color(57, 72, 98));
        lblNombreLider.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombreLider.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreLider.setText("Nombre del lider de partido");

        txtNombreLider.setBackground(new java.awt.Color(57, 72, 98));
        txtNombreLider.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNombreLider.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAtrasRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreLider, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreLider, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombrePartido, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombrePartido, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdeologia, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdeologia, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRegistroLayout.createSequentialGroup()
                            .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(lblIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSigla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSigla, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasRegistro)
                    .addComponent(btnGuardarRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombrePartido, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombrePartido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdeologia, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdeologia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreLider, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreLider, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelDerecho.add(panelRegistro, "card2");

        jSplitPane1.setRightComponent(panelDerecho);

        javax.swing.GroupLayout panelRegistroDeDatosLayout = new javax.swing.GroupLayout(panelRegistroDeDatos);
        panelRegistroDeDatos.setLayout(panelRegistroDeDatosLayout);
        panelRegistroDeDatosLayout.setHorizontalGroup(
            panelRegistroDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        panelRegistroDeDatosLayout.setVerticalGroup(
            panelRegistroDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        panelPrincipal.setBackground(new java.awt.Color(81, 198, 186));
        panelPrincipal.setMaximumSize(new java.awt.Dimension(700, 450));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(700, 450));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(700, 450));

        btnRegistroDeDatos.setBackground(new java.awt.Color(57, 72, 98));
        btnRegistroDeDatos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRegistroDeDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroDeDatos.setText("REGISTRO DE DATOS");
        btnRegistroDeDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroDeDatosActionPerformed(evt);
            }
        });

        btnEdicionDeDatos.setBackground(new java.awt.Color(57, 72, 98));
        btnEdicionDeDatos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEdicionDeDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnEdicionDeDatos.setText("EDICION DE DATOS");

        jButton3.setBackground(new java.awt.Color(57, 72, 98));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("GRAFICAS ");

        pilar1.setBackground(new java.awt.Color(57, 72, 98));
        pilar1.setMaximumSize(new java.awt.Dimension(180, 450));
        pilar1.setMinimumSize(new java.awt.Dimension(180, 450));
        pilar1.setPreferredSize(new java.awt.Dimension(180, 450));

        javax.swing.GroupLayout pilar1Layout = new javax.swing.GroupLayout(pilar1);
        pilar1.setLayout(pilar1Layout);
        pilar1Layout.setHorizontalGroup(
            pilar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        pilar1Layout.setVerticalGroup(
            pilar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pilar2.setBackground(new java.awt.Color(57, 72, 98));
        pilar2.setMaximumSize(new java.awt.Dimension(180, 450));
        pilar2.setMinimumSize(new java.awt.Dimension(180, 450));
        pilar2.setPreferredSize(new java.awt.Dimension(180, 450));

        javax.swing.GroupLayout pilar2Layout = new javax.swing.GroupLayout(pilar2);
        pilar2.setLayout(pilar2Layout);
        pilar2Layout.setHorizontalGroup(
            pilar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        pilar2Layout.setVerticalGroup(
            pilar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(pilar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdicionDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(pilar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnRegistroDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnEdicionDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addComponent(pilar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pilar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelEdicionDeDatos.setMaximumSize(new java.awt.Dimension(700, 450));
        panelEdicionDeDatos.setMinimumSize(new java.awt.Dimension(700, 450));
        panelEdicionDeDatos.setPreferredSize(new java.awt.Dimension(700, 450));

        jSplitPane2.setBackground(new java.awt.Color(81, 198, 186));
        jSplitPane2.setDividerSize(0);
        jSplitPane2.setMaximumSize(new java.awt.Dimension(700, 450));
        jSplitPane2.setMinimumSize(new java.awt.Dimension(700, 450));
        jSplitPane2.setPreferredSize(new java.awt.Dimension(700, 450));

        panelIzquierdoE.setBackground(new java.awt.Color(81, 198, 186));
        panelIzquierdoE.setMaximumSize(new java.awt.Dimension(350, 450));
        panelIzquierdoE.setMinimumSize(new java.awt.Dimension(350, 450));
        panelIzquierdoE.setPreferredSize(new java.awt.Dimension(350, 450));
        panelIzquierdoE.setLayout(new java.awt.CardLayout());

        panelEdicionVista.setBackground(new java.awt.Color(81, 198, 186));
        panelEdicionVista.setMaximumSize(new java.awt.Dimension(350, 450));
        panelEdicionVista.setMinimumSize(new java.awt.Dimension(350, 450));

        lblTituloEdicion.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblTituloEdicion.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloEdicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloEdicion.setText("Edicion de Datos");

        lblTextoEdicion.setBackground(new java.awt.Color(81, 198, 186));
        lblTextoEdicion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTextoEdicion.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoEdicion.setText("En esta seccion puedes actualizar toda");

        lblTextoEdicion2.setBackground(new java.awt.Color(81, 198, 186));
        lblTextoEdicion2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTextoEdicion2.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoEdicion2.setText("la informacion de un partido politico.");

        panelTextoEdicion3.setBackground(new java.awt.Color(81, 198, 186));
        panelTextoEdicion3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        panelTextoEdicion3.setForeground(new java.awt.Color(255, 255, 255));
        panelTextoEdicion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTextoEdicion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconEdit.png"))); // NOI18N
        panelTextoEdicion3.setToolTipText("");

        javax.swing.GroupLayout panelEdicionVistaLayout = new javax.swing.GroupLayout(panelEdicionVista);
        panelEdicionVista.setLayout(panelEdicionVistaLayout);
        panelEdicionVistaLayout.setHorizontalGroup(
            panelEdicionVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicionVistaLayout.createSequentialGroup()
                .addGroup(panelEdicionVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEdicionVistaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblTituloEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEdicionVistaLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEdicionVistaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelEdicionVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTextoEdicion2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextoEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelTextoEdicion3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelEdicionVistaLayout.setVerticalGroup(
            panelEdicionVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicionVistaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloEdicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextoEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextoEdicion2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTextoEdicion3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        panelIzquierdoE.add(panelEdicionVista, "card2");

        jSplitPane2.setLeftComponent(panelIzquierdoE);

        panelDerechoE.setBackground(new java.awt.Color(57, 72, 98));
        panelDerechoE.setMaximumSize(new java.awt.Dimension(350, 450));
        panelDerechoE.setMinimumSize(new java.awt.Dimension(350, 450));
        panelDerechoE.setPreferredSize(new java.awt.Dimension(350, 450));
        panelDerechoE.setLayout(new java.awt.CardLayout());

        panelEdicion.setBackground(new java.awt.Color(57, 72, 98));
        panelEdicion.setMaximumSize(new java.awt.Dimension(350, 450));
        panelEdicion.setMinimumSize(new java.awt.Dimension(350, 450));

        btnAtrasEdit.setBackground(new java.awt.Color(81, 198, 186));
        btnAtrasEdit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAtrasEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasEdit.setText("<");
        btnAtrasEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasEditActionPerformed(evt);
            }
        });

        lblNombrePartidoEdit.setBackground(new java.awt.Color(57, 72, 98));
        lblNombrePartidoEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombrePartidoEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePartidoEdit.setText("Nombre del partido politico");

        txtNombrePartidoEdit.setBackground(new java.awt.Color(57, 72, 98));
        txtNombrePartidoEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNombrePartidoEdit.setForeground(new java.awt.Color(255, 255, 255));

        lblSiglaEdit.setBackground(new java.awt.Color(57, 72, 98));
        lblSiglaEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSiglaEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblSiglaEdit.setText("Sigla");

        txtSiglaEdit.setBackground(new java.awt.Color(57, 72, 98));
        txtSiglaEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSiglaEdit.setForeground(new java.awt.Color(255, 255, 255));
        txtSiglaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiglaEditActionPerformed(evt);
            }
        });

        lblNombreLiderEdit.setBackground(new java.awt.Color(57, 72, 98));
        lblNombreLiderEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombreLiderEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreLiderEdit.setText("Nombre del lider");

        txtNombreLiderEdit.setBackground(new java.awt.Color(57, 72, 98));
        txtNombreLiderEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNombreLiderEdit.setForeground(new java.awt.Color(255, 255, 255));

        lblIdeologiaEdit.setBackground(new java.awt.Color(57, 72, 98));
        lblIdeologiaEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblIdeologiaEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblIdeologiaEdit.setText("Ideologia");

        txtIdeologiaEdit.setBackground(new java.awt.Color(57, 72, 98));
        txtIdeologiaEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtIdeologiaEdit.setForeground(new java.awt.Color(255, 255, 255));

        lblNumeroAfiliadosEdit.setBackground(new java.awt.Color(57, 72, 98));
        lblNumeroAfiliadosEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNumeroAfiliadosEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroAfiliadosEdit.setText("Numero de afiliados");

        txtNumeroAfiliadosEdit.setBackground(new java.awt.Color(57, 72, 98));
        txtNumeroAfiliadosEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNumeroAfiliadosEdit.setForeground(new java.awt.Color(255, 255, 255));

        lblDepartamentoEdit.setBackground(new java.awt.Color(57, 72, 98));
        lblDepartamentoEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDepartamentoEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartamentoEdit.setText("Departamento");

        txtDepartamentoEdit.setBackground(new java.awt.Color(57, 72, 98));
        txtDepartamentoEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtDepartamentoEdit.setForeground(new java.awt.Color(255, 255, 255));

        btnGuardarEdit.setBackground(new java.awt.Color(81, 198, 186));
        btnGuardarEdit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnGuardarEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEdit.setText("Guardar");

        javax.swing.GroupLayout panelEdicionLayout = new javax.swing.GroupLayout(panelEdicion);
        panelEdicion.setLayout(panelEdicionLayout);
        panelEdicionLayout.setHorizontalGroup(
            panelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAtrasEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEdicionLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDepartamentoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartamentoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroAfiliadosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroAfiliadosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdeologiaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdeologiaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreLiderEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreLiderEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSiglaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSiglaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrePartidoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombrePartidoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        panelEdicionLayout.setVerticalGroup(
            panelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasEdit)
                    .addComponent(btnGuardarEdit))
                .addGap(24, 24, 24)
                .addComponent(lblNombrePartidoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombrePartidoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSiglaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSiglaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreLiderEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreLiderEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdeologiaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdeologiaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroAfiliadosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroAfiliadosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDepartamentoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDepartamentoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        panelDerechoE.add(panelEdicion, "card2");

        jSplitPane2.setRightComponent(panelDerechoE);

        javax.swing.GroupLayout panelEdicionDeDatosLayout = new javax.swing.GroupLayout(panelEdicionDeDatos);
        panelEdicionDeDatos.setLayout(panelEdicionDeDatosLayout);
        panelEdicionDeDatosLayout.setHorizontalGroup(
            panelEdicionDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEdicionDeDatosLayout.setVerticalGroup(
            panelEdicionDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTablaEdicion.setMaximumSize(new java.awt.Dimension(700, 450));
        panelTablaEdicion.setMinimumSize(new java.awt.Dimension(700, 450));
        panelTablaEdicion.setPreferredSize(new java.awt.Dimension(700, 450));

        jSplitPane3.setDividerSize(0);
        jSplitPane3.setMaximumSize(new java.awt.Dimension(700, 450));
        jSplitPane3.setMinimumSize(new java.awt.Dimension(700, 450));
        jSplitPane3.setPreferredSize(new java.awt.Dimension(700, 450));

        panelIzquierdoT.setBackground(new java.awt.Color(81, 198, 186));
        panelIzquierdoT.setMaximumSize(new java.awt.Dimension(350, 450));
        panelIzquierdoT.setMinimumSize(new java.awt.Dimension(350, 450));
        panelIzquierdoT.setPreferredSize(new java.awt.Dimension(350, 450));
        panelIzquierdoT.setLayout(new java.awt.CardLayout());

        panelTablaVista.setBackground(new java.awt.Color(81, 198, 186));
        panelTablaVista.setForeground(new java.awt.Color(255, 255, 255));
        panelTablaVista.setMaximumSize(new java.awt.Dimension(350, 450));
        panelTablaVista.setMinimumSize(new java.awt.Dimension(350, 450));

        lblTituloTabla.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblTituloTabla.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTabla.setText("Tabla de ID");

        lblTextoT1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTextoT1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoT1.setText("En esta seccion puedes ver identificadores");

        lblTextoT2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTextoT2.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoT2.setText("de los partidos y editarlos posteriormente.");

        lblIconTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconTabla.png"))); // NOI18N

        javax.swing.GroupLayout panelTablaVistaLayout = new javax.swing.GroupLayout(panelTablaVista);
        panelTablaVista.setLayout(panelTablaVistaLayout);
        panelTablaVistaLayout.setHorizontalGroup(
            panelTablaVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaVistaLayout.createSequentialGroup()
                .addGroup(panelTablaVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTablaVistaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelTablaVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextoT2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextoT1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIconTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTablaVistaLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelTablaVistaLayout.setVerticalGroup(
            panelTablaVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaVistaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblTextoT1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextoT2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblIconTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelIzquierdoT.add(panelTablaVista, "card2");

        jSplitPane3.setLeftComponent(panelIzquierdoT);

        panelDerechoT.setBackground(new java.awt.Color(57, 72, 98));
        panelDerechoT.setMaximumSize(new java.awt.Dimension(350, 450));
        panelDerechoT.setMinimumSize(new java.awt.Dimension(350, 450));
        panelDerechoT.setPreferredSize(new java.awt.Dimension(350, 450));
        panelDerechoT.setLayout(new java.awt.CardLayout());

        panelTabla.setBackground(new java.awt.Color(57, 72, 98));
        panelTabla.setForeground(new java.awt.Color(255, 255, 255));
        panelTabla.setMaximumSize(new java.awt.Dimension(350, 450));
        panelTabla.setMinimumSize(new java.awt.Dimension(350, 450));

        btnAtrasTabla.setBackground(new java.awt.Color(81, 198, 186));
        btnAtrasTabla.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAtrasTabla.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasTabla.setText("<");

        btnValidarTabla.setBackground(new java.awt.Color(81, 198, 186));
        btnValidarTabla.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnValidarTabla.setForeground(new java.awt.Color(255, 255, 255));
        btnValidarTabla.setText("Validar");

        tablaIdentificador.setBackground(new java.awt.Color(57, 72, 98));
        tablaIdentificador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tablaIdentificador.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tablaIdentificador.setForeground(new java.awt.Color(255, 255, 255));
        tablaIdentificador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Identificador", "Nombre Partido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaIdentificador.setSelectionBackground(new java.awt.Color(81, 198, 186));
        tablaIdentificador.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrollTabla.setViewportView(tablaIdentificador);

        lblIdentificadorTabla.setBackground(new java.awt.Color(57, 72, 98));
        lblIdentificadorTabla.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblIdentificadorTabla.setForeground(new java.awt.Color(255, 255, 255));
        lblIdentificadorTabla.setText("Validar identificador");

        txtIdentificadorTabla.setBackground(new java.awt.Color(57, 72, 98));
        txtIdentificadorTabla.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtIdentificadorTabla.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAtrasTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValidarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdentificadorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(lblIdentificadorTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasTabla)
                    .addComponent(btnValidarTabla))
                .addGap(30, 30, 30)
                .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdentificadorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdentificadorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        panelDerechoT.add(panelTabla, "card2");

        jSplitPane3.setRightComponent(panelDerechoT);

        javax.swing.GroupLayout panelTablaEdicionLayout = new javax.swing.GroupLayout(panelTablaEdicion);
        panelTablaEdicion.setLayout(panelTablaEdicionLayout);
        panelTablaEdicionLayout.setHorizontalGroup(
            panelTablaEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTablaEdicionLayout.setVerticalGroup(
            panelTablaEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistroDeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelEdicionDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelTablaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistroDeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelEdicionDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelTablaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasRegistroActionPerformed

    private void txtIdeologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdeologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdeologiaActionPerformed

    private void txtNumAfiliadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAfiliadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAfiliadosActionPerformed

    private void txtNombrePartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePartidoActionPerformed

    private void txtFechaFundacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFundacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFundacionActionPerformed

    private void btnRegistroDeDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroDeDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroDeDatosActionPerformed

    private void btnAtrasEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasEditActionPerformed

    private void txtSiglaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiglaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiglaEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtrasEdit;
    public javax.swing.JButton btnAtrasRegistro;
    public javax.swing.JButton btnAtrasTabla;
    public javax.swing.JButton btnEdicionDeDatos;
    public javax.swing.JButton btnGuardarEdit;
    public javax.swing.JButton btnGuardarRegistro;
    public javax.swing.JButton btnRegistroDeDatos;
    public javax.swing.JButton btnValidarTabla;
    public javax.swing.JButton jButton3;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    public javax.swing.JLabel lblDepartamento;
    public javax.swing.JLabel lblDepartamentoEdit;
    public javax.swing.JLabel lblFechaFundacion;
    private javax.swing.JLabel lblIconRegistro;
    public javax.swing.JLabel lblIconTabla;
    public javax.swing.JLabel lblIdentificador;
    public javax.swing.JLabel lblIdentificadorTabla;
    public javax.swing.JLabel lblIdeologia;
    public javax.swing.JLabel lblIdeologiaEdit;
    public javax.swing.JLabel lblNombreLider;
    public javax.swing.JLabel lblNombreLiderEdit;
    public javax.swing.JLabel lblNombrePartido;
    public javax.swing.JLabel lblNombrePartidoEdit;
    public javax.swing.JLabel lblNumAfiliados;
    public javax.swing.JLabel lblNumeroAfiliadosEdit;
    public javax.swing.JLabel lblSigla;
    public javax.swing.JLabel lblSiglaEdit;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    public javax.swing.JLabel lblTextoEdicion;
    public javax.swing.JLabel lblTextoEdicion2;
    public javax.swing.JLabel lblTextoT1;
    public javax.swing.JLabel lblTextoT2;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lblTituloEdicion;
    public javax.swing.JLabel lblTituloTabla;
    public javax.swing.JPanel panelDerecho;
    public javax.swing.JPanel panelDerechoE;
    private javax.swing.JPanel panelDerechoT;
    public javax.swing.JPanel panelEdicion;
    public javax.swing.JPanel panelEdicionDeDatos;
    public javax.swing.JPanel panelEdicionVista;
    public javax.swing.JPanel panelIzquierdo;
    public javax.swing.JPanel panelIzquierdoE;
    public javax.swing.JPanel panelIzquierdoT;
    public javax.swing.JPanel panelPrincipal;
    public javax.swing.JPanel panelRegistro;
    public javax.swing.JPanel panelRegistroDeDatos;
    public javax.swing.JPanel panelRegistroVista;
    public javax.swing.JPanel panelTabla;
    public javax.swing.JPanel panelTablaEdicion;
    public javax.swing.JPanel panelTablaVista;
    public javax.swing.JLabel panelTextoEdicion3;
    private javax.swing.JPanel pilar1;
    private javax.swing.JPanel pilar2;
    public javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaIdentificador;
    public javax.swing.JTextField txtDepartamento;
    public javax.swing.JTextField txtDepartamentoEdit;
    public javax.swing.JTextField txtFechaFundacion;
    public javax.swing.JTextField txtIdentificador;
    public javax.swing.JTextField txtIdentificadorTabla;
    public javax.swing.JTextField txtIdeologia;
    public javax.swing.JTextField txtIdeologiaEdit;
    public javax.swing.JTextField txtNombreLider;
    public javax.swing.JTextField txtNombreLiderEdit;
    public javax.swing.JTextField txtNombrePartido;
    public javax.swing.JTextField txtNombrePartidoEdit;
    public javax.swing.JTextField txtNumAfiliados;
    public javax.swing.JTextField txtNumeroAfiliadosEdit;
    public javax.swing.JTextField txtSigla;
    public javax.swing.JTextField txtSiglaEdit;
    // End of variables declaration//GEN-END:variables
}
