/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.democrapp.view;

/**
 *
 * @author DIEGO
 */
public class TablaEdicionDeDatos extends javax.swing.JPanel {

    /**
     * Creates new form EdicionDeDatos
     */
    public TablaEdicionDeDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTablaEdicion = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();
        lblIconEdit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAtras = new javax.swing.JButton();
        lblCodigoIdentificador = new javax.swing.JLabel();
        txtCodigoIdentificador = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        scrollTablaID = new javax.swing.JScrollPane();
        tableIdentificador = new javax.swing.JTable();

        setBackground(new java.awt.Color(57, 72, 98));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 450));
        setMinimumSize(new java.awt.Dimension(700, 450));

        jPanelTablaEdicion.setBackground(new java.awt.Color(81, 198, 186));
        jPanelTablaEdicion.setMaximumSize(new java.awt.Dimension(350, 450));
        jPanelTablaEdicion.setMinimumSize(new java.awt.Dimension(350, 450));
        jPanelTablaEdicion.setPreferredSize(new java.awt.Dimension(350, 450));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Edicion de Datos");

        lblDescripcion1.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDescripcion1.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion1.setText("En esta seccion puedes actualizar toda la");

        lblDescripcion2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDescripcion2.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion2.setText("informacion de un partido politico.");

        lblIconEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconEdit.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 8));

        javax.swing.GroupLayout jPanelTablaEdicionLayout = new javax.swing.GroupLayout(jPanelTablaEdicion);
        jPanelTablaEdicion.setLayout(jPanelTablaEdicionLayout);
        jPanelTablaEdicionLayout.setHorizontalGroup(
            jPanelTablaEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaEdicionLayout.createSequentialGroup()
                .addGroup(jPanelTablaEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTablaEdicionLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblTitulo))
                    .addGroup(jPanelTablaEdicionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelTablaEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTablaEdicionLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTablaEdicionLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblIconEdit)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanelTablaEdicionLayout.setVerticalGroup(
            jPanelTablaEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaEdicionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitulo)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion2)
                .addGap(60, 60, 60)
                .addComponent(lblIconEdit)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        btnAtras.setBackground(new java.awt.Color(81, 198, 186));
        btnAtras.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("<");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lblCodigoIdentificador.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblCodigoIdentificador.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoIdentificador.setText("Codigo identificador");

        txtCodigoIdentificador.setBackground(new java.awt.Color(57, 72, 98));
        txtCodigoIdentificador.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtCodigoIdentificador.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoIdentificadorActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(81, 198, 186));
        btnSiguiente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");

        tableIdentificador.setBackground(new java.awt.Color(57, 72, 98));
        tableIdentificador.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        tableIdentificador.setForeground(new java.awt.Color(255, 255, 255));
        tableIdentificador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Identificador", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableIdentificador.setGridColor(new java.awt.Color(255, 255, 255));
        tableIdentificador.setMaximumSize(new java.awt.Dimension(300, 80));
        tableIdentificador.setMinimumSize(new java.awt.Dimension(300, 80));
        tableIdentificador.setPreferredSize(new java.awt.Dimension(300, 80));
        tableIdentificador.setSelectionBackground(new java.awt.Color(57, 72, 98));
        tableIdentificador.setSelectionForeground(new java.awt.Color(57, 72, 98));
        scrollTablaID.setViewportView(tableIdentificador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTablaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSiguiente)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCodigoIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodigoIdentificador))
                            .addComponent(scrollTablaID, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAtras)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTablaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTablaID, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigoIdentificador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtCodigoIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoIdentificadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel jPanelTablaEdicion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigoIdentificador;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblIconEdit;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrollTablaID;
    private javax.swing.JTable tableIdentificador;
    private javax.swing.JTextField txtCodigoIdentificador;
    // End of variables declaration//GEN-END:variables
}
