/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.democrapp.view;

/**
 *
 * @author 59173
 */
public class visualizacionDetallada extends javax.swing.JPanel {

    /**
     * Creates new form visualizacionDetallada
     */
    public visualizacionDetallada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        btnAtrasRegistro = new javax.swing.JButton();
        btnGuardarRegistro = new javax.swing.JButton();
        txtSigla1 = new javax.swing.JTextField();
        lblIdentificador1 = new javax.swing.JLabel();
        lblNombrePartido1 = new javax.swing.JLabel();
        txtNombrePartido1 = new javax.swing.JTextField();
        txtSigla2 = new javax.swing.JTextField();
        txtNombreLider1 = new javax.swing.JTextField();
        txtIdentificador1 = new javax.swing.JTextField();
        lblIdeologia1 = new javax.swing.JLabel();
        lblSigla1 = new javax.swing.JLabel();
        lblFechaFundacion1 = new javax.swing.JLabel();
        txtFechaFundacion1 = new javax.swing.JTextField();
        txtDepartamento1 = new javax.swing.JTextField();
        txtNumAfiliados1 = new javax.swing.JTextField();
        lblDepartamento1 = new javax.swing.JLabel();
        lblNombreLider1 = new javax.swing.JLabel();
        txtIdeologia1 = new javax.swing.JTextField();
        lblNumAfiliados1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        panelRegistro.setBackground(new java.awt.Color(57, 72, 98));
        panelRegistro.setMaximumSize(new java.awt.Dimension(350, 450));
        panelRegistro.setMinimumSize(new java.awt.Dimension(350, 450));

        btnAtrasRegistro.setBackground(new java.awt.Color(81, 198, 186));
        btnAtrasRegistro.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnAtrasRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasRegistro.setText(" < volver");
        btnAtrasRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasRegistroActionPerformed(evt);
            }
        });

        btnGuardarRegistro.setBackground(new java.awt.Color(81, 198, 186));
        btnGuardarRegistro.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnGuardarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarRegistro.setText("Guardar");
        btnGuardarRegistro.setToolTipText("");
        btnGuardarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRegistroActionPerformed(evt);
            }
        });

        txtSigla1.setBackground(new java.awt.Color(57, 72, 98));
        txtSigla1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSigla1.setForeground(new java.awt.Color(204, 204, 255));
        txtSigla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSigla1ActionPerformed(evt);
            }
        });

        lblIdentificador1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblIdentificador1.setForeground(new java.awt.Color(255, 255, 255));
        lblIdentificador1.setText("Identificador");

        lblNombrePartido1.setBackground(new java.awt.Color(57, 72, 98));
        lblNombrePartido1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombrePartido1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePartido1.setText("Nombre del partido");

        txtNombrePartido1.setBackground(new java.awt.Color(57, 72, 98));
        txtNombrePartido1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNombrePartido1.setForeground(new java.awt.Color(255, 255, 255));
        txtNombrePartido1.setText("Partido Democrático Nacional");
        txtNombrePartido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePartido1ActionPerformed(evt);
            }
        });

        txtSigla2.setBackground(new java.awt.Color(57, 72, 98));
        txtSigla2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSigla2.setForeground(new java.awt.Color(255, 255, 255));
        txtSigla2.setText("PDN");
        txtSigla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSigla2ActionPerformed(evt);
            }
        });

        txtNombreLider1.setBackground(new java.awt.Color(57, 72, 98));
        txtNombreLider1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNombreLider1.setForeground(new java.awt.Color(255, 255, 255));

        txtIdentificador1.setBackground(new java.awt.Color(57, 72, 98));
        txtIdentificador1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtIdentificador1.setForeground(new java.awt.Color(255, 255, 255));
        txtIdentificador1.setText("PT-2023-0042");
        txtIdentificador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificador1ActionPerformed(evt);
            }
        });

        lblIdeologia1.setBackground(new java.awt.Color(57, 72, 98));
        lblIdeologia1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblIdeologia1.setForeground(new java.awt.Color(255, 255, 255));
        lblIdeologia1.setText("Ideologia");
        lblIdeologia1.setToolTipText("");

        lblSigla1.setBackground(new java.awt.Color(57, 72, 98));
        lblSigla1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSigla1.setForeground(new java.awt.Color(255, 255, 255));
        lblSigla1.setText("Sigla");

        lblFechaFundacion1.setBackground(new java.awt.Color(57, 72, 98));
        lblFechaFundacion1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblFechaFundacion1.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaFundacion1.setText("Fecha de Fundacion YYYY-MM-DD");

        txtFechaFundacion1.setBackground(new java.awt.Color(57, 72, 98));
        txtFechaFundacion1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtFechaFundacion1.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaFundacion1.setText("1985-06-15");
        txtFechaFundacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFundacion1ActionPerformed(evt);
            }
        });

        txtDepartamento1.setBackground(new java.awt.Color(57, 72, 98));
        txtDepartamento1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtDepartamento1.setForeground(new java.awt.Color(255, 255, 255));
        txtDepartamento1.setText("DEP-05-CENTRAL");

        txtNumAfiliados1.setBackground(new java.awt.Color(57, 72, 98));
        txtNumAfiliados1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNumAfiliados1.setForeground(new java.awt.Color(255, 255, 255));
        txtNumAfiliados1.setText("125,347");
        txtNumAfiliados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAfiliados1ActionPerformed(evt);
            }
        });

        lblDepartamento1.setBackground(new java.awt.Color(57, 72, 98));
        lblDepartamento1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDepartamento1.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartamento1.setText("ID de departamento");

        lblNombreLider1.setBackground(new java.awt.Color(57, 72, 98));
        lblNombreLider1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombreLider1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreLider1.setText("Nombre del lider de partido");

        txtIdeologia1.setBackground(new java.awt.Color(57, 72, 98));
        txtIdeologia1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtIdeologia1.setForeground(new java.awt.Color(255, 255, 255));
        txtIdeologia1.setText("Centro-Derecha");
        txtIdeologia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdeologia1ActionPerformed(evt);
            }
        });

        lblNumAfiliados1.setBackground(new java.awt.Color(57, 72, 98));
        lblNumAfiliados1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNumAfiliados1.setForeground(new java.awt.Color(255, 255, 255));
        lblNumAfiliados1.setText("Numero de afiliados");

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSigla1)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(btnAtrasRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(btnGuardarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRegistroLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblIdeologia1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdeologia1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreLider1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreLider1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumAfiliados1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDepartamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombrePartido1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombrePartido1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumAfiliados1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaFundacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaFundacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRegistroLayout.createSequentialGroup()
                                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdentificador1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdentificador1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSigla1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSigla2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasRegistro)
                    .addComponent(btnGuardarRegistro))
                .addGap(18, 18, 18)
                .addComponent(txtSigla1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRegistroLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIdentificador1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSigla1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdentificador1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSigla2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblDepartamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtDepartamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblNombrePartido1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtNombrePartido1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblNombreLider1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtNombreLider1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblIdeologia1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtIdeologia1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(lblNumAfiliados1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtNumAfiliados1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblFechaFundacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtFechaFundacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(81, 198, 186));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Visualizacion Detallada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasRegistroActionPerformed

    private void btnGuardarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarRegistroActionPerformed

    private void txtSigla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSigla1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSigla1ActionPerformed

    private void txtNombrePartido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePartido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePartido1ActionPerformed

    private void txtSigla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSigla2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSigla2ActionPerformed

    private void txtIdentificador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificador1ActionPerformed

    private void txtFechaFundacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFundacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFundacion1ActionPerformed

    private void txtNumAfiliados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAfiliados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAfiliados1ActionPerformed

    private void txtIdeologia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdeologia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdeologia1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtrasRegistro;
    public javax.swing.JButton btnGuardarRegistro;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblDepartamento1;
    public javax.swing.JLabel lblFechaFundacion1;
    public javax.swing.JLabel lblIdentificador1;
    public javax.swing.JLabel lblIdeologia1;
    public javax.swing.JLabel lblNombreLider1;
    public javax.swing.JLabel lblNombrePartido1;
    public javax.swing.JLabel lblNumAfiliados1;
    public javax.swing.JLabel lblSigla1;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JPanel panelRegistro;
    public javax.swing.JTextField txtDepartamento1;
    public javax.swing.JTextField txtFechaFundacion1;
    public javax.swing.JTextField txtIdentificador1;
    public javax.swing.JTextField txtIdeologia1;
    public javax.swing.JTextField txtNombreLider1;
    public javax.swing.JTextField txtNombrePartido1;
    public javax.swing.JTextField txtNumAfiliados1;
    public javax.swing.JTextField txtSigla1;
    public javax.swing.JTextField txtSigla2;
    // End of variables declaration//GEN-END:variables
}
